services:
  restapp:
    depends_on:
      - redisService
    image: ${DOCKER_TAG}
    container_name: restapp
    restart: always
    ports:
      - 5000:5000
    networks:
     - appnetwork

  redisService:
    image: redis:alpine 
    ports:
      - 6379:6379
    networks:
     - appnetwork

networks:
  appnetwork: