name: CI

on:
  push:
    branches: ["andreCarpio_p2_dev", "andreCarpio_p2_base"]
  pull_request:
    branches: ["andreCarpio_p2_dev", "andreCarpio_p2_base"]

  workflow_dispatch:

env:
  SEM_VERSION: ""
  IMAGE_NAME: ""

jobs:
  ## 🔧 1.
  Static-codecheck:
    runs-on: self-hosted

    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Get dependencies
        run: pip install --requirement requirements.txt
      - name: Run Unit Tests
        run: python -m pytest test/unit -v
      
