name: CI

on:
  push:
    branches: ["andreCarpio_p2_dev", "andreCarpio_p2_base"]
  pull_request:
    branches: ["andreCarpio_p2_dev", "andreCarpio_p2_base"]

  workflow_dispatch:

env:
  SEM_VERSION: ${{github.run_id}}
  IMAGE_NAME: "restapp"
  BRANCH: ${{ (github.head_ref || github.ref_name) }}

jobs:
  ## 🔧 1.
  Static-codecheck:
    runs-on: self-hosted

    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Get dependencies
        run: pip install --requirement requirements.txt
      - name: Run Unit Tests
        run: python -m pytest test/unit -v

  ## 🔧 2.
  Build:
    runs-on: self-hosted
    needs: Static-codecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build image
        run: |
          $tag = "andrecarpio/$env:IMAGE_NAME:$env:BRANCH.ToLower()-1.0.$env:SEM_VERSION"
          docker build -t $tag .
      - name: push registry
        run: |
          $tag = "andrecarpio/$env:IMAGE_NAME:$env:BRANCH.ToLower()-1.0.$env:SEM_VERSION"
          docker push $tag

  ## 🚀 3.
  deploy-dev:
    runs-on: self-hosted
    needs: Build
    environment:
      name: Develop
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  ## 🚀 4.
  deploy-prod:
    runs-on: self-hosted
    needs: deploy-dev
    environment:
      name: Production
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
